version: '2'
services:
  nginx-proxy:
    restart: always
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    networks:
      - nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  power-outage-monitor:
    build: ./
    restart: always
    image: local/power-outage-monitor
    networks:
     - nginx-proxy
    environment:
     - VIRTUAL_HOST=power-api.quokka.ninja
    volumes:
     - ./power-outage-monitor/sites:/home/sites
  oec:
    restart: always
    image: oec:latest
    volumes:
     - /home/jle/src/PowerOutageMonitor/opsgenie:/home/opsgenie
    environment:
     - OEC_CONF_SOURCE_TYPE=local
     - OEC_CONF_LOCAL_FILEPATH=/home/opsgenie/conf/oec-config.yaml
networks:
  nginx-proxy:
    external:
      name: nginx-proxy
