web:
  port: 8000


gis-api:
  headers: 
  params:
    # buffer distance for input geometry
    distance: "30"

    # response format
    f: "json"

    # precision (decimal places) of RETURNED geometry
    geometryPrecision: "6"

    # returned fields 
    outFields: "OBJECTID, UtilityCompany, StartDate, EstimatedRestoreDate, Cause, ImpactedCustomers, County, OutageStatus, OutageType, GlobalID, IncidentId"
    
    # output spatial relation to return longitude, latitude values
    outSR: "4326"

    # units for distance parameter, other options: esriSRUnit_Meter | esriSRUnit_StatuteMile | esriSRUnit_Foot | esriSRUnit_Kilometer | esriSRUnit_NauticalMile | esriSRUnit_USNauticalMile
    unit: "esriSRUnit_Meter"

    where: "1=1"


pge-api:
  headers: 
  params:
    regionType: "city"
    expand: "true"


sce-api:
  # wait time, in seconds, for HTML elements to appear
  maxWaitTime: 5


date-time:
  # timezone to return, find more at: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
  timezone: "America/Los_Angeles"
  timeFormat: "%m/%d/%Y %I:%M:%S %p %Z"


logger:
  logLevel: "DEBUG"
  fileName: "test"
  sysLog:
    host: "logs.papertrailapp.com"
    port: 49638


geocode:
  # more at: https://developers.arcgis.com/rest/geocode/api-reference/geocoding-find-address-candidates.htm
  headers:
  params:
    f: "json"
    outFields: "location"
    
  # minimum accuracy of address (inclusive)
  minScore: 97


sqlite3:
  dbName: "sites/site.db"

